apiVersion: apps/v1
kind: Deployment
metadata:
  name: vertx-cluster-deployment
spec:
  selector:
    matchLabels:
      app: vertx-cluster
  replicas: 0
  template:
    metadata:
      labels:
        app: vertx-cluster
    spec:
      containers:
      - name: vertx-cluster
        image: gcr.io/rise-164421/vertx-cluster:latest
        ports:
        - containerPort: 7070
